import { NextResponse } from 'next/server';

const minecraftPlans = [
  {
    id: 'mc-starter',
    name: 'Starter',
    description: 'Perfect for small private servers with friends',
    ramGb: 2,
    cpuCores: 2,
    storageGb: 10,
    playerSlots: 20,
    monthlyPriceCents: 800,
    features: [
      '2 GB RAM',
      '2 vCPU Cores',
      '10 GB NVMe Storage',
      'Up to 20 Players',
      'Java & Bedrock Support',
      'Automatic Backups',
      'DDoS Protection',
      'Modpack Support',
      'Plugin Support',
      'Web-based Control Panel',
      'Instant Setup',
      '24/7 Monitoring',
    ],
    isPopular: false,
  },
  {
    id: 'mc-standard',
    name: 'Standard',
    description: 'Great for growing communities and public servers',
    ramGb: 4,
    cpuCores: 3,
    storageGb: 20,
    playerSlots: 50,
    monthlyPriceCents: 1500,
    features: [
      '4 GB RAM',
      '3 vCPU Cores',
      '20 GB NVMe Storage',
      'Up to 50 Players',
      'Java & Bedrock Support',
      'Automatic Daily Backups',
      'DDoS Protection',
      'Modpack Support (CurseForge, FTB, etc.)',
      'Plugin Support (Spigot, Paper, Purpur)',
      'Web-based Control Panel',
      'Instant Setup',
      '24/7 Monitoring',
      'Priority Support',
    ],
    isPopular: true,
  },
  {
    id: 'mc-pro',
    name: 'Professional',
    description: 'For large communities and modded networks',
    ramGb: 8,
    cpuCores: 4,
    storageGb: 40,
    playerSlots: 100,
    monthlyPriceCents: 3000,
    features: [
      '8 GB RAM',
      '4 vCPU Cores',
      '40 GB NVMe Storage',
      'Up to 100 Players',
      'Java & Bedrock Support',
      'Automatic Hourly Backups',
      'Advanced DDoS Protection',
      'Modpack Support (All Launchers)',
      'Plugin Support (All Forks)',
      'Web-based Control Panel',
      'Instant Setup',
      '24/7 Monitoring',
      'Priority Support',
      'Custom JVM Flags',
      'Database Included (MySQL/PostgreSQL)',
    ],
    isPopular: false,
  },
  {
    id: 'mc-enterprise',
    name: 'Enterprise',
    description: 'Dedicated resources for networks and hosting providers',
    ramGb: 16,
    cpuCores: 6,
    storageGb: 80,
    playerSlots: 200,
    monthlyPriceCents: 6000,
    features: [
      '16 GB RAM',
      '6 vCPU Cores (Dedicated)',
      '80 GB NVMe Storage',
      'Up to 200+ Players',
      'Java & Bedrock Support',
      'Automatic 15-min Backups',
      'Premium DDoS Protection',
      'Unlimited Modpacks & Plugins',
      'Web-based Control Panel',
      'Instant Setup',
      '24/7 Monitoring',
      'Priority Support',
      'Custom JVM Flags',
      'Database Included (MySQL/PostgreSQL/MongoDB)',
      'Redis Cache Included',
      'Custom Domain & SSL',
      'SLA Guarantee',
    ],
    isPopular: false,
  },
];

export async function GET() {
  return NextResponse.json({ plans: minecraftPlans });
}